# Generated by Django 3.1.5 on 2021-03-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
