# Generated by Django 3.1.3 on 2021-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210305_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='task',
            field=models.TextField(default=''),
        ),
    ]
