# Generated by Django 3.1.3 on 2021-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210403_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
