# Generated by Django 3.1.3 on 2020-12-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(default=None, max_length=50)),
                ('book_description', models.CharField(default=None, max_length=500)),
                ('book_image', models.ImageField(default='', upload_to='cat_img')),
                ('book_rates', models.IntegerField(default=5)),
                ('book_commit_id', models.IntegerField()),
                ('book_data', models.CharField(max_length=100000)),
                ('book_upload_date', models.DateTimeField(verbose_name='date published')),
                ('book_publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_title', models.CharField(max_length=50)),
                ('cat_img', models.ImageField(default=None, upload_to='cat_img')),
                ('cat_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
