# Generated by Django 3.0.6 on 2020-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default=None, max_length=50)),
                ('book_description', models.CharField(default=None, max_length=500)),
                ('book_image', models.CharField(max_length=500)),
                ('book_rates', models.IntegerField(default=5)),
                ('book_commit_id', models.IntegerField(max_length=20)),
                ('book_publish', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
