# Generated by Django 3.1.3 on 2020-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data_book',
            field=models.FileField(default=None, upload_to='', verbose_name='zip_data'),
        ),
    ]
