# Generated by Django 3.0.6 on 2020-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_commit_id',
            field=models.IntegerField(),
        ),
    ]
