# Generated by Django 3.1.3 on 2021-01-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_book_data_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postid', models.IntegerField(max_length=40)),
                ('title', models.CharField(max_length=500)),
                ('img_pub_date', models.DateTimeField(verbose_name='date published')),
                ('img', models.ImageField(default='', upload_to='cat_img/content')),
            ],
        ),
    ]
