# Generated by Django 3.1.3 on 2021-01-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_imgupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='postid',
            field=models.IntegerField(),
        ),
    ]
