# Generated by Django 3.1 on 2020-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_auto_20200627_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_category', models.CharField(max_length=50)),
                ('book_img', models.ImageField(default=None, upload_to='cat_img')),
                ('cat_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
