# Generated by Django 3.1.3 on 2021-01-07 05:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_auto_20210107_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_arrcat',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
