# Generated by Django 3.1.2 on 2020-10-26 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_auto_20200826_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='book_category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
