# Generated by Django 3.1.2 on 2020-10-28 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_auto_20201026_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_data',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
    ]
