# Generated by Django 3.1.5 on 2021-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_auto_20210107_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_data',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
