# Generated by Django 3.1.2 on 2020-10-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_book_book_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_upload_date',
        ),
    ]
