# Generated by Django 3.1.5 on 2021-01-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_auto_20210108_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='keyboard',
            field=models.CharField(default='', max_length=50),
        ),
    ]
