# Generated by Django 3.1.5 on 2021-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_auto_20210125_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='keyboard',
            field=models.CharField(default='', max_length=200),
        ),
    ]
