# Generated by Django 3.1.5 on 2021-01-23 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_auto_20210117_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.BigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
