# Generated by Django 3.1.5 on 2021-01-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_auto_20210125_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
