# Generated by Django 3.1.5 on 2021-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.BigIntegerField(default=1),
        ),
    ]
