# Generated by Django 3.1.5 on 2021-01-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_auto_20210125_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='keyboard',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
