# Generated by Django 3.1.5 on 2021-01-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0019_auto_20210125_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.CharField(default='hell', max_length=100),
            preserve_default=False,
        ),
    ]
