# Generated by Django 3.1.5 on 2021-02-03 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0020_book_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_arrcatstr',
            field=models.CharField(default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_arrcat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1], size=None),
        ),
    ]
