# Generated by Django 3.1.5 on 2021-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0022_auto_20210203_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.CharField(max_length=300),
        ),
    ]
