# Generated by Django 3.1.5 on 2021-02-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0025_dislike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='user',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=60),
        ),
    ]
