# Generated by Django 3.1.5 on 2021-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0030_auto_20210305_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_data',
            field=models.TextField(),
        ),
    ]
