# Generated by Django 3.1.5 on 2021-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0031_auto_20210309_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.CharField(default=None, max_length=100000),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(default=None, max_length=100000),
        ),
        migrations.AlterField(
            model_name='book',
            name='keyboard',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
