# Generated by Django 3.1.5 on 2021-03-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0032_auto_20210309_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(max_length=500),
        ),
    ]
