# Generated by Django 3.2.9 on 2021-11-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0034_auto_20210324_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=1000)),
                ('shipping', models.CharField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='specifications',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='admin_dashboard.Tag'),
        ),
    ]
