# Generated by Django 3.2.9 on 2021-12-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0035_auto_20211127_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
