# Generated by Django 3.2.9 on 2021-12-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0037_alter_book_book_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_data',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
