# Generated by Django 3.2.9 on 2021-12-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0038_alter_book_book_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='model',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
