# Generated by Django 3.2.9 on 2021-12-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0039_book_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='data_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
