# Generated by Django 3.2.9 on 2021-12-05 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0040_auto_20211205_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=1000), size=None),
        ),
    ]
