# Generated by Django 3.1 on 2020-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rregister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('school_name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=6)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('birth', models.DateTimeField()),
                ('adhaar_card', models.IntegerField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('address' , models.CharField(max_length=500)),

            ],
        ),
    ]
