# Generated by Django 3.1.3 on 2020-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_plople',
            field=models.BooleanField(default=False),
        ),
    ]
