# Generated by Django 3.1.2 on 2020-10-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rregister',
            name='adhaar_card',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rregister',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
