# Generated by Django 3.1.2 on 2020-10-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201015_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='rregister',
            name='password',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
