# Generated by Django 3.1.2 on 2020-10-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201020_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
