# Generated by Django 3.1.5 on 2021-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20210123_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myueers',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
