# Generated by Django 3.1.5 on 2021-01-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20210123_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myueers',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
