# Generated by Django 3.1.5 on 2021-01-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20210123_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myueers',
            name='mobile_no',
            field=models.BigIntegerField(default=1),
        ),
    ]
