# Generated by Django 3.1.5 on 2021-01-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20210123_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myueers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
