# Generated by Django 3.1.5 on 2021-02-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('myuser', '0007_myueers_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myueers',
            name='student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myueers',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='404_user.png', upload_to='user')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('teacher', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False)),
                ('mobile_no', models.BigIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='404_user.png', upload_to='user')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('teacher', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False)),
                ('class_id', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.school')),
            ],
        ),
    ]
