# Generated by Django 3.1.5 on 2021-02-21 02:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_auto_20210219_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=1, size=None),
            preserve_default=False,
        ),
    ]
